/*
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.CreateDashboard;
import io.swagger.client.model.CreateEntry;
import io.swagger.client.model.CreateSeries;
import io.swagger.client.model.HTTPValidationError;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for DefaultApi
 */
@Ignore
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    /**
     * Create Dashboard
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createDashboardDashboardsPostTest() throws Exception {
        CreateDashboard body = null;
        Object response = api.createDashboardDashboardsPost(body);

        // TODO: test validations
    }
    /**
     * Create Entry
     *
     * creates a new entry to a series if it exists &amp; the request contains a valid token   :param request: :param data: :return:
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createEntryEntriesPostTest() throws Exception {
        CreateEntry body = null;
        Object response = api.createEntryEntriesPost(body);

        // TODO: test validations
    }
    /**
     * New Series
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void newSeriesSeriesPostTest() throws Exception {
        CreateSeries body = null;
        Object response = api.newSeriesSeriesPost(body);

        // TODO: test validations
    }
}
