//
// CreateSeries.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CreateSeries: Codable {

    public var name: String
    public var dashboard: String
    public var _description: String?
    public var meta: Any?

    public init(name: String, dashboard: String, _description: String? = nil, meta: Any? = nil) {
        self.name = name
        self.dashboard = dashboard
        self._description = _description
        self.meta = meta
    }

    public enum CodingKeys: String, CodingKey { 
        case name
        case dashboard
        case _description = "description"
        case meta
    }

}
