//
// CreateDashboard.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CreateDashboard: Codable {

    public var name: String
    public var project: String
    public var tags: [Any]?
    public var _description: String?
    public var meta: Any?

    public init(name: String, project: String, tags: [Any]? = nil, _description: String? = nil, meta: Any? = nil) {
        self.name = name
        self.project = project
        self.tags = tags
        self._description = _description
        self.meta = meta
    }

    public enum CodingKeys: String, CodingKey { 
        case name
        case project
        case tags
        case _description = "description"
        case meta
    }

}
