//
// CreateEntry.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CreateEntry: Codable {

    public var series: String
    public var data: Any
    public var meta: Any?

    public init(series: String, data: Any, meta: Any? = nil) {
        self.series = series
        self.data = data
        self.meta = meta
    }


}
