/*
 * FastAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CreateSeries struct {
	Name string `json:"name"`
	Dashboard string `json:"dashboard"`
	Description string `json:"description,omitempty"`
	Meta *interface{} `json:"meta,omitempty"`
}
