/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param series 
 * @param &#x60;data&#x60; 
 * @param meta 
 */
data class CreateEntry (

    val series: kotlin.String,
    val `data`: kotlin.Any,
    val meta: kotlin.Any? = null
) {
}