/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param name 
 * @param project 
 * @param tags 
 * @param description 
 * @param meta 
 */
data class CreateDashboard (

    val name: kotlin.String,
    val project: kotlin.String,
    val tags: kotlin.Array<kotlin.Any>? = null,
    val description: kotlin.String? = null,
    val meta: kotlin.Any? = null
) {
}