name: Build Python SDK
on:
  push:
    branches:
      - main

jobs:
  generate-python-client:
    runs-on: ubuntu-latest
    name: Build SDK
    steps:
      # Checkout your code
      - name: Checkout
        uses: actions/checkout@v2

      # Generate your OpenAPI document (if you don't write it manually)

      # Use the action to generate a client package
      # This uses the default path for the openapi document and thus assumes there is an openapi.json in the current workspace.
      - name: Generate Python Client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: python

      - name: Publish SDK
        uses: seanmiddleditch/gha-publish-to-git@master
        with:
          branch: latest
          github_token: "${{ secrets.GITHUB_TOKEN  }}"
          source_folder: ./

        if: success() && github.event == 'push'
